baseurl: http://propertycross.com

name: PropertyCross
description: Helping you select a cross-platform mobile framework
githuburl: https://github.com/tastejs/PropertyCross

platforms:
  android: Android
  ios: iOS

extensions:
  android: APK
  ios: IPA

blogurl: http://blog.tastejs.com/
