baseurl: http://bdimitrov-sl.github.io/PropertyCross-Site-Redesign/

name: PropertyCross
description: Helping you select a cross-platform mobile framework
githuburl: https://github.com/tastejs/PropertyCross

platforms:
  android: Android
  ios: iOS

extensions:
  android: apk
  ios: ipa

blogurl: http://blog.tastejs.com/
